### ISSUE TITLE
No means by which to unlock a SmartPlug in 'Locked' mode.

### ISSUE THREAD

**Issue by andydvsn** [jamesleesaunders/PyAlertMe#46]
When a SmartPlug is put into 'Locked' mode, there is no apparent way to unlock it other than resetting the plug. Requesting 'Normal' mode doesn't remove the lock.

**Comment by jamesleesaunders** [comment]
Hi Andy, this is something I could not work our myself either! I ended up steering clear of locked mode as, like you say, it is a pain in the bum to get out of this mode. If you do find the answer it would be great to hear.

**Comment by andydvsn** [comment]
Cool, thanks. Good to know I wasn't just glossing over something. I'll add that to my list along with the battery level!
