### ISSUE TITLE
How do we read the battery voltage from a device?

### ISSUE THREAD

**Issue by andydvsn** [jamesleesaunders/PyAlertMe#47]
In the AlertMe API it's possible to pull the current battery voltage reading. Is this possible when communicating directly with the device?

**Comment by jamesleesaunders** [comment]
Hi Andy, Great idea! I am afraid I don't know. If you can figure out which Cluster ID / Cluster Cmd may contain the battery level numbers that would be brill!

**Comment by andydvsn** [comment]
Heck, that sounds like a challenge. I'll read back through your blog posts to try and figure out how you figured out the ones we have at the moment - I have what you might describe as a 'dunce' level of understanding of Zigbee right now, so I need to try and step it up!
