### ISSUE TITLE
Any code for the Lamp?

### ISSUE THREAD

**Issue by andydvsn** [jamesleesaunders/PyAlertMe#49]
Just noticed that the README says that there's support for the Lamp device, but I can't spot any code for it.

**Comment by jamesleesaunders** [comment]
Hi Andrew, 
The hub supports all the devices listed in the readme:

* SmartPlug
* Power Clamp
* Button Device
* PIR Device
* Door/Window sensor
* Alarm Detector
* Keyfob Device
* Beacon
* Lamp

There is not a class (yet) to simulate BEING a lamp, but the hub supports connecting TO a lamp. The only end device I have created a class for is a SmartPlug (see: zbsmartplug.py), it would not be too difficult to create a zblamp.py class (pretty much a copy of the zbsmartplug class).

There is not really any code per-se for the lamp other than in the unit test here:
https://github.com/jamesleesaunders/PyAlertMe/blob/092100104d7affdd12afcc45b8a66c608ec711e4/tests/test_zbnode.py#L366
Here you will see all the different devices I have tested against the hub.

Hope this helps,

Jim

**Comment by jamesleesaunders** [comment]
I also managed to get a Mathmos AlertMe Lamp. But as of yet not managed to control it.

AlertMe actually released 2 versions of their Lamp (aka Beacon): 
one was designed in conjunction with Mathmos (really nice design & quality look and feel) looks like the ‘Audki’ range.
The other was a cheaper, plastic looking design which was not as well built.
I have one of each version.
