### ISSUE TITLE
Use real AlertMe hub hardware?

### ISSUE THREAD

**Issue by probonopd** [jamesleesaunders/PyAlertMe#58]
Is it possible to use the real AlertMe hub hardware and run Python and PyAlertMe on it (instead of a ZigBee) or is it basically an expensive brick at this time?

**Comment by jrjefferies** [comment]
No, not the real Alertme hub, we are using a  PI with a xbee module.  I believe the hub uses a different zigbee module.  I have managed to get reasonably far with hacking the real hub, but
 - I am still stuck in busybox 
 - if I could, i'm not ready to format it to get the PyAlertMe running

I maybe something I try in the future, when I have the library running better
Regards,
  JJ

**Comment by jrjefferies** [comment]
The real Alertme hub is already running Python and is written in Python (2.4).  I have got busybox root access on the device, but not real root access.
Info on getting into the hub can be found here
https://forum.alertme.org.uk/viewtopic.php?f=4&t=97
If you want to help on either the PyAlertMe development or getting full access to the hub, that would be welcome.
Regards,
  JJ

**Comment by probonopd** [comment]
Thanks for this pointer. Looking at that thread, I see mentions of ZigBee and Python, so maybe it's not impossible after all. Will look into it when I have time.
